### PANDAS SERIES
A series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index

### Creating Series 
There are multiple ways to create pandas series

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### Creating a dataFrame

In [20]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 30, 29, 42],
    'City': ['New York', 'Berlin', 'London', 'Paris'],
    'Salary': [65000, 70000, 62000, 850000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   30    Berlin   70000
2  Peter   29    London   62000
3  Linda   42     Paris  850000

In [19]:
data_list = [
  ['John', 'Anna', 'Peter', 'Linda'],
 [28, 30, 29, 42],
 ['New York', 'Berlin', 'London', 'Paris'],
 [65000, 70000, 62000, 850000]
]
df2 =pd.DataFrame(data_list)
df2

          0       1       2       3
0      John    Anna   Peter   Linda
1        28      30      29      42
2  New York  Berlin  London   Paris
3     65000   70000   62000  850000

In [28]:
data_list = [
 ['John', 28, 'New York', 65000],
 ['Anna', 32, 'Paris', 70000],
 ['Peter', 29, 'Berlin', 62000],
 ['Linda', 42, 'London', 85000]
]
df2 =pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selection and Indexing of Columns

In [32]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### creating a new column

In [35]:
df2["Designation"] = ["Doctor", "Engg.", "Doctor", "Engg."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   32     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

### removing a column

In [38]:
df2.drop('Designation', axis = 1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [40]:
df2.drop(["City","Salary"], axis = 1)

    Name  Age
0   John   28
1   Anna   32
2  Peter   29
3  Linda   42

### selecting rows

In [41]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   32     Paris   70000

In [43]:
df.loc[3]

Name       Linda
Age           42
City       Paris
Salary    850000
Name: 3, dtype: object

### selecting subsets of rows and columns

In [45]:
df.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1    Berlin   70000

In [46]:
df.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

#### conditional selection

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
# i only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   32   Paris   70000
3  Linda   42  London   85000

In [52]:
# i only want to see those people whose age is above 30 and their city should be paris
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   32  Paris   70000